### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by mhkamal15** [MrWaltz-b14/Argonify---#1]
Wait a sec, so this is like an actual app, like an APK file? Or is it a collection of Python scripts?

**Comment by mhkamal15** [comment]
Also, please remove the three dashes in the repo name.

**Comment by mhkamal15** [comment]
https://docs.google.com/document/d/1QvOZmAof6fMsM2PpM0OBMxfm7wmvil2lNsEk_HVQMEs/edit

**Comment by TopSlime999** [comment]
So let me explain better, you know wire shark right? how you open it an you can view ip adresses? like that bad instead the ip adresses are the connected phones. meaning they would be running a part of the app on their device without knowing. and by selecting that device you can either view what they are viewing or run other scripts. will probably be pretty difficult

**Comment by TopSlime999** [comment]
i just booted up with ubuntu

**Comment by mhkamal15** [comment]
YAY

**Comment by mhkamal15** [comment]
Oh. So this is spyware?

**Comment by TopSlime999** [comment]
cant open the docs you sent

**Comment by mhkamal15** [comment]
I think that’s borderline if not illegal, pal.

**Comment by TopSlime999** [comment]
yeah thats the goal

**Comment by mhkamal15** [comment]
I think i shared it, lemme check.

**Comment by TopSlime999** [comment]
obviously, so long as we dont use it on random people its perfectly legal

**Comment by mhkamal15** [comment]
Ok, try it now.

**Comment by mhkamal15** [comment]
Mr. Moore replied (see Argonify doc).
